### ISSUE TITLE
Missing properties for nested request body

### ISSUE THREAD

**Issue by justiniruuza** [rakutentech/laravel-request-docs#186]
Hi, thank you so much for the hard working on this awesome library

Right now, I have a issue with nested body request. It's missing a lot of properties. I have to add them manually. Could you take a look on it? 🙏 

![image](https://user-images.githubusercontent.com/96718437/223629178-008f1966-3a9a-445a-b9f8-d6d9f265e292.png)

**Comment by kevincobain2000** [comment]
Will check. You on latest version btw??

**Comment by justiniruuza** [comment]
Yes, in v2.11

**Comment by justiniruuza** [comment]
I also got another issue when upload image in nested request body. I cannot send the request, it always return result like the image(2) but I can send that request with postman successful (Image 3). Could you help check it too 🙏 

(1)
![image](https://user-images.githubusercontent.com/96718437/223682046-e83c3fcb-539e-467b-be92-ffed31ce1ab8.png)

(2)
![image](https://user-images.githubusercontent.com/96718437/223683102-77b7d769-5bfc-4ecd-8c42-4a21282e08d4.png)

(3)
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/96718437/223683324-2b9db981-2d75-4eff-9cb0-caacb5c9b89d.png">

**Comment by kevincobain2000** [comment]
Noted. Will address both by this week

**Comment by kevincobain2000** [comment]
About the file upload response issue. The one difference I see in Postman vs LRD is the trailing slash in the URI. 
On LRD it is `/api/posts` while on postman it is `/api/posts/`.
The URI field is editable on LRD, so can you try adding the `/` on the URI? Probably that is the issue, since you have got response 200, it could be a remove trailing slash that has caused a response body to be some sort of HTML instead of json...?

Will wait for your reply.


About the nested issue, I will check it now

**Comment by kevincobain2000** [comment]
ah ok 
About the nested properties issue.

Root cause: lazy

Following needs to be fixed. Right now it only takes first nest into the account.

https://github.com/rakutentech/laravel-request-docs/blob/97c75f56b5917585a0f87fd082ad540ce501bb20/ui/src/components/ApiAction.tsx#L233-L241


You can submit a pull req? I won't be able to do that until 2 weeks, little occupied.

**Comment by justiniruuza** [comment]
Thank for your reply, will look into it when I have some time!
