### ISSUE TITLE
[BUG] Unexpected token '<', "<!doctype "... is not valid JSON

### ISSUE THREAD

**Issue by zkenstein** [rakutentech/laravel-request-docs#209]
**Describe the bug**

**To Reproduce**
1. `composer create-project laravel/laravel:^10.0 laravel`
2. `composer require rakutentech/laravel-request-docs`
3. `php artisan serve`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]

**Versions (please complete the following information):**
- Laravel Version:
- PHP Version:
- Laravel Request Docs Version:

**Additional context**
Got this error after following installation step by step

**Comment by kevincobain2000** [comment]
What does the config look like? And what’s the output of /request-docs/api?

**Comment by cleitokarloh** [comment]
@zkenstein

This error present because any route had error... or you forget any method in controller of the Route::resource. 

Please, in config/request-docs.php set debug `true` and open your project accessing `your-project/request-docs/`

Open the  Chrome inspector and see network tab. 

- See the error of request.
- fixes that
- run `php artisan route:cache`
- try again... if this error persist repeat this process until all works fine.

**Comment by kevincobain2000** [comment]
Closing as no response
