### ISSUE TITLE
Headers that is checked in middleware 

### ISSUE THREAD

**Issue by trongio** [rakutentech/laravel-request-docs#322]
I have a middleware that checks for token.
The Authorization header is Required.
but the needed header does not show up in documentation.

maybe add extra documentation support for middleware?

**Comment by kevincobain2000** [comment]
same as https://github.com/rakutentech/laravel-request-docs/issues/321

To both @trongio  san and @dade1987 

Currently the frontend doesn't communicate with user specific config on Laravel `config/request-docs.php`
In order to implement this, I'd need to update the frontend, so it can obtain desired information from user as pre-loaded. 
Sorry, I haven't had time to implement due to busy with many other projects and life.
I'd be open to pull reqs or please wait til I get some time off hands and push these features.

**Comment by kevincobain2000** [comment]
Fixed in [v2.31](https://github.com/rakutentech/laravel-request-docs/releases/tag/v2.31)
