### ISSUE TITLE
Documentation Naming

### ISSUE THREAD

**Issue by rawahamid** [rakutentech/laravel-request-docs#332]
**Doc name**
I checked the old commits it has document name to change documentation title and name but i have a question what is the reason for remove document name in the config file?
Removed commit link [#ece5754](https://github.com/rakutentech/laravel-request-docs/commit/a6421e3c89a1f4c0a5589f7d78103e40fc1522fe)

Screenshot
<img width="918" alt="Screenshot 2024-02-04 at 16 33 52" src="https://github.com/rakutentech/laravel-request-docs/assets/27570598/5fc6411c-2a5b-4809-b663-f2e3606466d2">

**Comment by kevincobain2000** [comment]
The reason is that now the frontend is an SPA instead of blade, and the entire static site is built as release static. Therefore, in order to communicate with what's in the config of PHP, we will need to develop a separate API.
I am a single man maintaining this project, a lot of people have requested have with no one submitting a pull req. Hence the issue is still open.
Hope that helped.

**Comment by kevincobain2000** [comment]
Fixed in [v2.31](https://github.com/rakutentech/laravel-request-docs/releases/tag/v2.31)
