### ISSUE TITLE
Not able to upload files

### ISSUE THREAD

**Issue by manoj-xelp** [rakutentech/laravel-request-docs#353]
Hi, 
I am trying to upload a file. it's returning an HTML content response. Even if any validation error it returns the same.

![WhatsApp Image 2024-04-24 at 1 34 38 PM (2)](https://github.com/rakutentech/laravel-request-docs/assets/83335281/ee37fc94-1857-4023-ad9e-592d68688789)
![WhatsApp Image 2024-04-24 at 1 34 38 PM (1)](https://github.com/rakutentech/laravel-request-docs/assets/83335281/61217915-5cc0-4a76-95eb-c89507ed2baa)
![WhatsApp Image 2024-04-24 at 1 34 38 PM](https://github.com/rakutentech/laravel-request-docs/assets/83335281/213e7755-0866-436b-b4c1-2b547f5e3034)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : chrome
 - Version :22

**Versions (please complete the following information):**
- Laravel Version:10
- PHP Version:8.1
- Laravel Request Docs Version:2.35

**Comment by kevincobain2000** [comment]
Thanks. If you have an idea about this bug, feel free to submit a or. Or wait for a while until I have a look and fix it. Won’t be soon.

**Comment by Plong-Wasin** [comment]
> Thanks. If you have an idea about this bug, feel free to submit a PR. Or wait for a while until I have a look and fix it. Won’t be soon.

The issue might be caused by this line:

https://github.com/rakutentech/laravel-request-docs/blob/dc003526eba0fe747197c309c2adbc6fd7308ed6/ui/src/components/ApiAction.tsx#L92
This line removes the Accept: application/json header, which results in a redirect to the /request-docs page if validation fails. The reason for overriding to multipart/form-data is unclear.

@manoj-xelp As a temporary workaround, you can change the header from `Accept` to `accept`.

**Comment by kevincobain2000** [comment]
Thanks @Plong-Wasin
