### ISSUE TITLE
Create separate docs based on scopes

### ISSUE THREAD

**Issue by pouyasalimi** [rakutentech/laravel-request-docs#66]
What a nice package, I am enjoying it, But one little thing I want to have is:
I have different API scopes in my project, some of them are for interacting with the front app, some of them are for mobile and etc.

The package should have a config for separating scopes and for a big project it is better to categorize APIs.

**Comment by kevincobain2000** [comment]
Hi @pouyasalimi 
Thanks for the issue and thanks for using this package. I am glad it made you a little more productive.

This is an issue, I have been battling with, reference here: https://github.com/rakutentech/laravel-request-docs/issues/44#issuecomment-1040233830

Currently, I receive a list of routes as raw from `collect(Route::getRoutes())`
Sample below

```
       Illuminate\Routing\Route {#3931
         +uri: "mobile/api/v1/health",
         +methods: [
           "GET",
           "HEAD",
         ],
         +action: [
           "middleware" => [
             "mobileapi",
           ],
           "uses" => "App\Http\Controllers\MobileApi\V1\HealthController@index",
           "controller" => "App\Http\Controllers\MobileApi\V1\HealthController@index",
           "namespace" => "App\Http\Controllers",
           "where" => [],
           "as" => "generated::HJasdasdasdDPsmH",
           "prefix" => "mobile/api",
         ],
```

The issue here is how to go about categorizing. There can be many keys to choose from in order to do it scope based. Such as, by prefix, by middleware, by methods etc. If you have good suggestion for it.

**Comment by pouyasalimi** [comment]
Aha, I see.

Putting a search box above the page is very helpful, but separating API scops is another thing. 

For example, when I have a monolith laravel backend that handles separate scops of APIs and depending on the team, I don't want to share Admin API's with my mobile app team. So just like the [Laravel swagger package](https://github.com/DarkaOnLine/L5-Swagger/blob/master/config/l5-swagger.php), we should have multiple config for multiple API scopes and we can build our documents according to the config file.

**Comment by pouyasalimi** [comment]
I have a little free time these days and if you think I can help, let me know.

**Comment by pouyasalimi** [comment]
Yes, that's correct, will send a PR.

**Comment by kevincobain2000** [comment]
Closing for now....Good feature tho.
Only open to pull req on this
