### ISSUE TITLE
Type and everything is ignored when Rule class is used in rules

### ISSUE THREAD

**Issue by SagarNaliyapara** [rakutentech/laravel-request-docs#83]
```
    public function rules(): array
    {
        return [
            'name' => [
                'required',
                'string',
                Rule::unique('accounts', 'name')
                    ->where('user_id', $this->user()->id),
            ],
        ]
    }
```

When there is a Rule class is used it shows everything empty in type, nullable, rules etc.

![Screenshot 2022-09-08 at 6 18 32 PM](https://user-images.githubusercontent.com/11518462/189125748-5290c2e5-301c-42f5-8c7e-3629371e8580.png)

Thanks for amazing package @kevincobain2000

**Comment by kevincobain2000** [comment]
That’s a difficult one to solve. Let me see what I can do.

**Comment by SagarNaliyapara** [comment]
Weird if when it is defined it also ignores rest of the rules, if we can still have rest of the rules in documentation then that would be awesome

**Comment by kevincobain2000** [comment]
Hi @SagarNaliyapara 
Thanks for waiting.

Short response:

```
   $this->user()?->id
```

By doing this it should be able to fetch the rest of the rules except the `Rule`

Long answer:

`Rule` itself doesn't cause the disappearance of other rules. 
Rest of the rules get ignored because entire block is failed when `$this->user()` is called as it might be null at the time `/request-docs` are opened. Null checking inside the rule should help.

Alternatively, you can add a middleware to the `config/request-docs.php` which can set such missing model objects, in your case `$this->user` to something.

```
    'middlewares' => [
        //Example
        // \App\Http\Middleware\NotFoundWhenProduction::class,
    ],
```

**Comment by SagarNaliyapara** [comment]
Thanks for the detailed explanation, will definitely try do something like that and if that works well then PR soon as well ❤️

**Comment by kevincobain2000** [comment]
I think I have found where the issue was, I ll have pushed the new tag **1.24**, please update and re-try.

Thanks for reporting

**Comment by SagarNaliyapara** [comment]
I noticed we need to use optional helper or null safe operator when there is exception to get validation in documentation
