### ISSUE TITLE
Response does not work

### ISSUE THREAD

**Issue by chcnetconsulting** [rakutentech/laravel-request-docs#97]

**Comment by chcnetconsulting** [comment]
Hi
First of all, thanks for your fine extension. I can use it perfectly for Postman. Although there is a tiny bug, The Responses of Requests are measured, but not shown below the "try" button, as on your demo page. Don't you know about any issues with Laravel 9?  Idea how to fix that?
Kind regards
Christoph

**Comment by chcnetconsulting** [comment]
Probably I have found out the reason - if the laravel .env config file does not contain APP_DEBUG=true ANS APP_ENV=dev, it does not show up....  Probably something for the docu? 👍 

Thank you
have a nice day :-)

**Comment by chcnetconsulting** [comment]
Just 1 tiny bugfix: row 133, index.blade.php - 

style="width:max-content" renders not correctly - width: 100% does, what it should in safari and chrome

**Comment by kevincobain2000** [comment]
You are right

https://github.com/rakutentech/laravel-request-docs/blob/b8bef5124c0961c16b2237123d1ac144db4a4727/src/LaravelRequestDocsMiddleware.php#L16

`APP_DEBUG=true` must be set to true in order to listen, as listening to DB queries on prod and response times is an overhead, therefore it is disabled. 

> style="width:max-content" renders not correctly - width: 100% does

That's a quick fix, if you can submit a pull req, I ll merge it straight away. Otherwise, give me a day or two and I ll push that change soon.

**Comment by chcnetconsulting** [comment]
Take your time. I’m fine, to update, when you tell me, you incorporated the quick fix.

**Comment by kevincobain2000** [comment]
Width issue fixed in #124
